In [4]:
import numpy as np
import plotly.graph_objects as go
from abc_env_stoch import ABCflow
from naive_agents import DoNothing, FixedPhi


In [9]:
def plot_agent_trajectory(agent, sep_size=0.02*np.pi, seed=1):
    env = ABCflow(sep_size, seed=seed, kappa=1)
    print(env.passive)
    print(env.active)
    active = np.array([]).reshape(0, 3)
    passive = np.array([]).reshape(0, 3)
    
    while not env.isOver():
        active = np.vstack((active, env.active))
        passive = np.vstack((passive, env.passive))
        state = env.getState()
        action = agent.sample_action(state)
        env.step(action)
    
    fig = go.Figure(data=go.Scatter3d(
        x=passive[:,0],
        y=passive[:,1],
        z=passive[:,2],
        mode='lines',
        name = "passive"
      )
    )
    
    fig.add_trace(go.Scatter3d(
        x=active[:,0],
        y=active[:,1],
        z=active[:,2],
        mode='lines',
        name = "active"
      )
    )
    print(env.passive)
    print(env.active)
    fig.show()

In [10]:
do_nothing = DoNothing()
plot_agent_trajectory(do_nothing,seed=2)

[1.64375752 1.87547517 5.11593121]
[1.59015213 1.88862424 5.14595462]
[ 1.74646449 11.91620065  4.70572323]
[ 1.70978213 11.82948275  4.62460456]
